FLCN-138
bcgov/parks_reso-public pull request #12
Opened 2021-06-07 17:42 UTC by MaxWardle

Updated styling to match bc gov

2021-06-08 19:17 UTC, cameronpettit requested changes

2021-06-08 19:17 UTC, cameronpettit commented on src/app/registration/success/success.component.html
> +<button type="button" class="float-right BC-Gov-PrimaryButton" (click)="navigate()">Home</button>
spacing feels a bit off with the back arrow icon

2021-06-08 19:17 UTC, cameronpettit commented on src/assets/base/base.scss
> +@media (min-width: 576px) {
consolidate entries for @media of same min-width

2021-06-09 18:24 UTC, MaxWardle commented on src/app/pass-lookup/pass-lookup-form/pass-lookup-form.component.html
> +    <button class="BC-Gov-PrimaryButton" [disabled]="lookupForm.invalid" (click)="onSubmit()">Send Email</button>
added disabled button bcgov styling

2021-06-09 18:41 UTC, MaxWardle commented on src/assets/base/base.scss
> +    font-family: ‘BCSans’, ‘Noto Sans’, Verdana, Arial, sans-serif;
added bc sans properly

2021-06-09 18:42 UTC, MaxWardle commented on src/app/header/header.component.html
> +        <li><a href=".">Resources</a></li>
removed links for now, left the navbar for future use and to match styling

2021-06-10 00:12 UTC, mtCarto approved these changes

2021-06-10 21:08 UTC, marklise commented
Just a drive-by here, we should be using padding/margin etc for bootstrap classes instead of hardcoding those values in to custom classes.

2021-06-14 01:10 UTC, cameronpettit requested changes

2021-06-14 01:10 UTC, cameronpettit commented on src/assets/base/base.scss
> +    font-family: ‘BCSans’, ‘Noto Sans’, Verdana, Arial, sans-serif;
Site still does not display BC Sans font

2021-06-14 01:10 UTC, cameronpettit commented on src/assets/base/base.scss
> +.BC-Gov-PrimaryButton {
button styling classes should overrule bootstrap `btn-*` classes - `btn-primary`, `btn-secondary`, etc as per mark's comment (typ)

2021-06-14 01:10 UTC, cameronpettit commented on src/assets/base/base.scss
> +        margin-top: 60px;
hard-coding spacing values may cause issues with adaptive display - use bootstrap spacing classes in angular template files instead. (typ)

2021-06-25 17:14 UTC, closed without merging

2021-06-25 17:19 UTC, MaxWardle commented
Closed because most of this has been addressed in other PRs since this was opened. Also some styling choices made here have been moved away from.